[project]
name = "sqs-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3-stubs[sqs]>=1.40.26",
    "obsv-tools>=0.1.0",
    "pydantic>=2.11.7",
]
